# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laboratorienoter fra Virkeligheden
email: mwormleonhard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Videnskab til og fra folket: Nørdede påfund og studier af og i den nære virkelighed. 
  Her bor køkkenkemien, baghavefysikken, altanastronomien, beregningerne fra bagsiden af kuverten, den lille undren og den mystiske viden.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mwormleonhard.github.io" # the base hostname & protocol for your site
twitter_username: wyrmlein
github_username:  mwormleonhard
googleplus_username: MartinWormLeonhard
phone: 27 12 70 42


# Build settings
markdown: kramdown

include: 
  - _YeQaHRt-W0
  - _JrxmXPFbx0
  

